//name all icons within the app see this folder and list them as a typescript enum see folder /icon
/*
 * CAUTION: This file is generated by `pnpm run scripts:generate-app-svg`
 * Do not edit this file manually. To add an illustration/icon, add an SVG file
 * to the illustrations or icons directory and re-run the script.
 */
import bottle from './bottle.svg';
import close from './close.svg';
import emptyBottle from './emptyBottle.svg';
import emptySpoon from './emptySpoon.svg';
import halfEllipse from './halfEllipse.svg';
import profileActive from './profileActive.svg';
import profileInActive from './profileInActive.svg';
import search from './search.svg';
import spoon from './spoon.svg';

export const iconNames = {
  search: search,
  spoon: spoon,
  bottle: bottle,
  close: close,
  emptyBottle: emptyBottle,
  emptySpoon: emptySpoon,
  halfEllipse: halfEllipse,
  profileActive: profileActive,
  profileInActive: profileInActive,
} as const;
